### ISSUE TITLE
Tap to dismiss

### ISSUE THREAD

**Issue by drivediary** [BastiaanJansen/toast-swift#12]
Hello - Thanks for this, really like it.

A little feature request. Please could you implement an option in the config for a 'tap to dismiss' option?

Cheers :)

**Comment by BastiaanJansen** [comment]
Hi! Glad you like it.

I currently don't have time to further develop toast-swift, but pull requests are welcome!

**Comment by BastiaanJansen** [comment]
@allen870619 has implemented the functionality!

**Comment by allen870619** [comment]
I didn't add the parameter into Config (Only `enablePanToClose`), so don't remember to call `toast.enableTapToClose()`
Seems the readme file has deleted the usage.
Maybe I should change the way of it? (Adding into config) 🤔

**Comment by BastiaanJansen** [comment]
You could add it to ToastConfiguration, but I prefer not to add it as a seperate public method you have to call.

**Comment by allen870619** [comment]
Ok. Same as I thought 😉
