### ISSUE TITLE
Custom toast view

### ISSUE THREAD

**Issue by Maverick1000** [BastiaanJansen/toast-swift#14]
On your code page you have an example for CustomToastView, could you add some sample code of what would go into the func createView(for toast: Toast).

**Comment by BastiaanJansen** [comment]
Hi, @Maverick1000,

Toast class just expects a ToastView, which can be any view as long as it implements the ToastView protocol. You could look at [this](https://github.com/BastiaanJansen/toast-swift/blob/main/Sources/Toast/ToastViews/AppleToastView/AppleToastView.swift) file to see how the default toast view is made.
