### ISSUE TITLE
Binary operator '>' cannot be applied to operands of type 'CGFloat' and 'Double'

### ISSUE THREAD

**Issue by FreakAzure** [BastiaanJansen/toast-swift#32]
On Toast.swift, line 256 throws an error saying "Binary operator '>' cannot be applied to operands of type 'CGFloat' and 'Double'".

**Comment by Nikoloutsos** [comment]
Hey @FreakAzure 👋  and thanks for reporting this. 
I could not reproduce this error. May you please share the swift version you are using?

**Comment by Nikoloutsos** [comment]
@BastiaanJansen May we please close this issue?
