### ISSUE TITLE
I have a problem. A really, really, big problem. 

### ISSUE THREAD

**Issue by eatwhales** [BastiaanJansen/toast-swift#34]
After the first popover pops up, click the button to pop up the second popover and repeat to N pop-ups. It's going to add up, the shadow looks heavy, and what I need is the first one to close when the second one pops up, so how do I do that?

**Comment by BastiaanJansen** [comment]
Stacking or queuing toasts are currently not supported. You should close your toast before showing another one.

PR's are of course welcome.

**Comment by eatwhales** [comment]
OK, thank you.

**Comment by Nikoloutsos** [comment]
Hello @eatwhales  👋 .
that sounds like a good idea.
I am thinking that we can build something similar to https://github.com/Daltron/NotificationBanner/blob/master/NotificationBanner/Classes/NotificationBannerQueue.swift

**Comment by League2EB** [comment]
This issue has still not been implemented. I would like to ask if anyone has any ideas?
@eatwhales  @BastiaanJansen

**Comment by BastiaanJansen** [comment]
Hi @League2EB, 

Queueing is now supported. When you are not using queues you should first hide the currently visible toast before showing the next one.

**Comment by League2EB** [comment]
> Hi @League2EB,
> 
> Queueing is now supported. When you are not using queues you should first hide the currently visible toast before showing the next one.

I don't plan to use Queueing, but I didn't see in your document how to hide the currently displayed Toast. Can you give me some hints? Thank you.
