### ISSUE TITLE
Number of lines option

### ISSUE THREAD

**Issue by efehelvaci** [BastiaanJansen/toast-swift#36]
It truncates the texts when they are too long. It would be good if we can set the number of lines in the config. Also, minimum scale factor can be useful too.

Especially needed when you don't use a subtitle but a long title.

![Screenshot 2023-08-11 at 21 30 01](https://github.com/BastiaanJansen/toast-swift/assets/12911212/ad82ffb3-45b9-4c28-be46-ef9245832b7a)

**Comment by mehulparmar4ever** [comment]
Any updates?

**Comment by joshid** [comment]
Same problem here. It would be nice to have at least 2 lines in subtitle...

**Comment by AbdelrahmanShehab** [comment]
how to add numberOfLines in ToastConfiguration?

**Comment by parmar-mehul** [comment]
Hello @AbdelrahmanShehab ,

Please use below updated repo,
https://github.com/mehulparmar4ever/toast-swift

**Comment by BastiaanJansen** [comment]
Number of lines is natively supported:

```swift
let toast = Toast.text("Safari pasted from Notes", viewConfig: .init(
    titleNumberOfLines: 2,
    subtitleNumberOfLines: 3
))
toast.show()
```
