### ISSUE TITLE
Background colour customisation 

### ISSUE THREAD

**Issue by francescoleoni98** [BastiaanJansen/toast-swift#38]
It would be useful to let developer choose the background colour of the toast

**Comment by twomedia** [comment]
The [AppleToastView](https://github.com/BastiaanJansen/toast-swift/blob/main/Sources/Toast/ToastViews/AppleToastView/AppleToastView.swift) class exposes the lightBackgroundColor & darkBackgroundColor in the initializer, so you can use those to change the background colors. 

I might create some convenience functions that include those & submit a PR, but in the meantime you can create your own using an extension.
