### ISSUE TITLE
Need toast message position ?

### ISSUE THREAD

**Issue by santespatel** [BastiaanJansen/Toast-Swift#4]
/* Its not a issue its suggestion */
–> it would be great if ya provide where to show toast like top, bottom, center .....
–> toast need a dynamic height like what if your title and subtile have more then 3 lines ?

thank you... its suggestion not a complain 🙂

**Comment by Nikoloutsos** [comment]
@BastiaanJansen Here is a PR that implements this 😄 
https://github.com/BastiaanJansen/toast-swift/pull/21
