### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by Prorokius** [BastiaanJansen/toast-swift#7]
Can I change font for Toast title?
No any information about this

**Comment by BastiaanJansen** [comment]
Hi, currently it is not possible to change the font to the existing toast views. You could of course create your own toast view with a different font.
(I think you could even extend the AppleToastView class and change the font, so you don't have to create the layout from scratch.)

**Comment by Nikoloutsos** [comment]
@BastiaanJansen I have an implementation that allows NSAttributedString.
Let me know if we want it so that I PR it.

**Comment by BastiaanJansen** [comment]
That would be great!

**Comment by Nikoloutsos** [comment]
I think this [PR ](https://github.com/BastiaanJansen/toast-swift/pull/23) resolves this issue 😄

**Comment by BastiaanJansen** [comment]
Thanks! It is included in version 1.2.0!
